### PR TITLE
Fix CJS interop

### PR DESCRIPTION
**Pull request by mskelton**
Was encountering some issues when using `expect-axe-playwright` and it seems related to broken CJS exports in this package.

### CODE REVIEW

**Comment by mskelton** [comment]
Hey friends! 👋

**Review by joephela — APPROVED** [review]
Hey @mskelton !

**Comment by mskelton** [comment]
@joephela Thanks for the approval, when you get a chance to merge and cut a release, I'll make a PR in `expect-axe-playwright` to get it updated to the latest of this package.

**Comment by joephela** [comment]
@mskelton our github actions are not triggering from your forked branch, we are looking into it.

**Comment by joephela** [comment]
@mskelton release should be good to go: https://github.com/Widen/axe-reporter-html/releases/tag/v2.0.0

**Comment by mskelton** [comment]
@joephela I'm flying home today from NYC, but I'll get it handled tomorrow.

**Pull request merged**
